name: docker back test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build compose file
      run: cd Back && docker-compose build

    - name: run containers
      run: cd Back && docker-compose up -d
    
    - name: test docker containers
      run: docker ps -a
    
    - name: test volume
      run: docker exec php-app ls -al

    - name: composer dependencies
      run: docker exec php-app composer install

    - name: phpunit test
      run: docker exec php-app XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text